import { Tag } from '~/models/Tag/tagSchema.js'; // Đường dẫn tới tagSchema
import { generateSlug } from '~/utils/common.js';

export const seedTags = async () => {
  try {
    // Xóa dữ liệu cũ trong collection Tag
    await Tag.deleteMany({});
    console.log('Old tags cleared');

    // Dữ liệu tag mẫu
    const tags = [
      { name: 'Breaking News', description: 'Latest updates and events', slug: '' },
      { name: 'Technology', description: 'Tech news and trends', slug: '' },
      { name: 'Sports', description: 'News about sports', slug: '' },
      { name: 'Economy', description: 'Economic updates', slug: '' },
      { name: 'Politics', description: 'Political news', slug: '' },
      { name: 'Education', description: 'Learning and education', slug: '' },
      { name: 'Health', description: 'Health tips and news', slug: '' },
      { name: 'Entertainment', description: 'Movies, music, and shows', slug: '' },
      { name: 'Science', description: 'Scientific news', slug: '' },
      { name: 'Environment', description: 'Climate and nature news', slug: '' },
      { name: 'Hot News', description: 'Popular news stories', slug: '' },
      { name: 'AI', description: 'Artificial intelligence updates', slug: '' },
      { name: '5G', description: 'Next-gen mobile networks', slug: '' },
      { name: 'Blockchain', description: 'Blockchain news', slug: '' },
      { name: 'CyberSecurity', description: 'Online security updates', slug: '' },
      { name: 'Augmented Technology', description: 'AR news and insights', slug: '' },
      { name: 'Quantum Computing', description: 'Advanced computing updates', slug: '' },
      { name: 'Mental Health', description: 'Mind and wellness tips', slug: '' },
      { name: 'Awareness', description: 'Important issues to know', slug: '' },
      { name: 'Diet', description: 'Healthy eating tips', slug: '' },
      { name: 'Nutrition', description: 'Food and health info', slug: '' },
      { name: 'Sleep', description: 'Rest and sleep tips', slug: '' },
      { name: 'Inflation', description: 'Price changes and news', slug: '' },
      { name: 'Global Economy', description: 'World economy updates', slug: '' },
      { name: 'Economic Growth', description: 'Business and growth news', slug: '' },
      { name: 'Global Trade', description: 'International trade updates', slug: '' },
      { name: 'Labor Market', description: 'Workforce and jobs news', slug: '' },
      { name: 'Cryptocurrency', description: 'Digital currency updates', slug: '' },
      { name: 'Digital Economy', description: 'Online economy trends', slug: '' },
      { name: 'Esports', description: 'Competitive gaming news', slug: '' },
      { name: 'Video Games', description: 'Gaming updates', slug: '' },
      { name: 'Video', description: 'Articles with Video', slug: '' },
      { name: 'Football', description: 'Football news', slug: '' },
      { name: 'Tactics', description: 'Game strategies', slug: '' },
      { name: "Women's Sports", description: "News on women's sports", slug: '' },
      { name: 'Equality', description: 'Equal rights updates', slug: '' },
      { name: 'Athlete Performance', description: 'Athlete stats and updates', slug: '' },
      { name: 'Training', description: 'Fitness and training tips', slug: '' },
      { name: 'Social Media', description: 'Social platforms updates', slug: '' },
      { name: 'Elections', description: 'Voting and election news', slug: '' },
      { name: 'Climate Change', description: 'Environmental updates', slug: '' },
      { name: 'Populism', description: 'Populist movements news', slug: '' },
      { name: 'Democracy', description: 'Democracy updates', slug: '' },
      { name: 'Diplomacy', description: 'International relations', slug: '' },
      { name: 'International Organizations', description: 'Global institutions news', slug: '' },
      { name: 'Basketball', description: 'News about basketball and players', slug: '' },
      { name: 'Music', description: 'Updates from the music industry', slug: '' },
      { name: 'Industry', description: 'Business and industrial news', slug: '' },
      { name: 'Kanye West', description: 'News and updates about Kanye West', slug: '' },
      { name: 'Culture', description: 'Cultural trends and events', slug: '' },
      { name: 'Hip Hop', description: 'Hip-hop music and culture', slug: '' },
      { name: 'Rock', description: 'Rock music news and trends', slug: '' },
      { name: 'Pop', description: 'Pop music updates and stars', slug: '' },
      { name: 'Film', description: 'Movies and filmmaking news', slug: '' },
      { name: 'Hollywood', description: 'Hollywood news and updates', slug: '' },
      { name: 'Netflix', description: 'Updates about Netflix and its shows', slug: '' },
      { name: 'Movies', description: 'News and reviews about movies', slug: '' },
      { name: 'Oscars', description: 'Updates on the Oscars ceremony', slug: '' },
      { name: 'Academy Awards', description: 'Details about the Academy Awards', slug: '' },
      { name: 'Cars', description: 'News and updates about cars and the automotive industry', slug: '' },
      { name: 'Luxury', description: 'Trends and news about luxury lifestyles', slug: '' },
      { name: 'Lamborghini', description: 'Updates about Lamborghini cars and brand', slug: '' },
      { name: 'Ferrari', description: 'News about Ferrari cars and innovations', slug: '' },
      { name: 'Bugatti', description: 'Latest on Bugatti cars and developments', slug: '' },
      { name: 'Tesla', description: 'News about Tesla and its electric cars', slug: '' },
      { name: 'Electric Vehicles', description: 'Updates on electric cars and their technology', slug: '' },
      { name: 'Toyota', description: 'News and innovations from Toyota', slug: '' },
      { name: 'Innovation', description: 'Advancements and creative ideas in various fields', slug: '' },
      { name: 'Beefsteak', description: 'Delicious recipes and tips for cooking beefsteak', slug: '' },
      { name: 'Cuisine', description: 'Exploring food and culinary arts from around the world', slug: '' },
      { name: 'Cooking', description: 'Techniques, tips, and recipes for cooking', slug: '' },
      { name: 'Pho', description: 'News and recipes about the iconic Vietnamese dish', slug: '' },
      { name: 'Vietnamese', description: 'Exploring Vietnamese culture, food, and trends', slug: '' },
      { name: 'Fried Chicken', description: 'Delicious fried chicken recipes and trends', slug: '' },
      { name: 'Bacon', description: 'Everything about bacon: recipes, news, and tips', slug: '' },
      { name: 'Salad', description: 'Healthy and delicious salad recipes and tips', slug: '' },
      { name: 'Healthy', description: 'Tips and news for living a healthy lifestyle', slug: '' },
      { name: '2024 Elections', description: 'Coverage and updates on the 2024 elections', slug: '' },
      { name: 'Donald Trump', description: 'News and updates about Donald Trump', slug: '' },
      { name: 'Studying Abroad', description: 'Guides and tips for studying in a foreign country', slug: '' },
      { name: 'Cultural Exchange', description: 'Opportunities and benefits of cultural exchange programs', slug: '' },
      { name: 'Global Education', description: 'Trends and insights into education around the world', slug: '' },
      { name: 'Scholarships', description: 'Resources and advice on finding scholarships', slug: '' },
      { name: 'Financial Aid', description: 'Tips for securing financial support for education', slug: '' },
      { name: "Master's Degree", description: 'Guidance and news for pursuing a master’s degree', slug: '' },
      { name: 'Career', description: 'Career advice, trends, and resources for job seekers', slug: '' },
      { name: 'Computer Science', description: 'News and advancements in computer science', slug: '' },
      { name: 'Learning', description: 'Tips and resources for effective learning', slug: '' },
      { name: 'PhD', description: 'Insights and tips for pursuing a PhD program', slug: '' },
      { name: 'Doctorate', description: 'Guidance for obtaining a doctorate degree', slug: '' },
      { name: 'Apple', description: 'Latest news and updates about Apple products and services', slug: '' },
      { name: 'Samsung', description: 'News and trends about Samsung devices and technology', slug: '' },
      { name: 'Stock Market', description: 'Updates and insights into stock market trends', slug: '' },
      { name: 'Investing', description: 'Advice and news on smart investment strategies', slug: '' },
      { name: 'Finance', description: 'Financial news, tips, and trends', slug: '' },
      { name: 'Healthcare', description: 'News and developments in the healthcare industry', slug: '' },
      { name: 'Roger Federer', description: 'Updates and highlights about tennis legend Roger Federer', slug: '' },
      { name: 'Tennis', description: 'News, tips, and insights about tennis', slug: '' },
      { name: 'Rafael Nadal', description: 'News and updates on tennis star Rafael Nadal', slug: '' },
      { name: 'Novak Djokovic', description: "Highlights and updates on Novak Djokovic's career", slug: '' },
      { name: 'Relaxation', description: 'Tips and techniques for achieving relaxation and calmness', slug: '' },
      { name: 'Massage', description: 'Benefits and types of massages for health and relaxation', slug: '' },
      { name: 'Obesity', description: 'Health tips and news related to obesity management', slug: '' },
      { name: 'Stress', description: 'Ways to reduce stress and promote mental wellness', slug: '' },
      { name: 'Harry Potter', description: 'News and insights about the Harry Potter universe', slug: '' },
      { name: 'J.K. Rowling', description: 'Updates and works by author J.K. Rowling', slug: '' },
      { name: 'Literature', description: 'Exploring the world of books, poetry, and prose', slug: '' },
      { name: 'Comic Books', description: 'Updates and features on comic book releases and creators', slug: '' },
      { name: 'Graphic Novels', description: 'News and reviews of graphic novels and their creators', slug: '' },
      { name: 'Superheroes', description: 'News and stories about superhero characters and franchises', slug: '' },
      { name: 'Marvel', description: 'Updates on Marvel comics, movies, and characters', slug: '' },
      { name: 'DC', description: 'Latest news about DC comics and cinematic universe', slug: '' },
      { name: 'Sherlock Holmes', description: 'Stories and updates about the iconic detective', slug: '' },
      { name: 'Arthur Conan Doyle', description: 'Exploring the works and legacy of Arthur Conan Doyle', slug: '' },
      { name: 'Detective Fiction', description: 'News and reviews of detective and mystery fiction', slug: '' }
    ];

    for (const tag of tags) {
      tag.slug = generateSlug(tag.name);
    }

    // Chèn tag vào database
    const insertedTags = await Tag.insertMany(tags);

    // Hiển thị kết quả
    console.log('Tags seeded successfully');
  } catch (err) {
    console.error('Error seeding tags:', err);
  }
};
